### ISSUE TITLE
Game logic done + class object question

### ISSUE THREAD

**Issue by dainchatel** [dainchatel/aliendoctor#2]
Hey Vince, 

I misunderstood the directions and thought class objects were strongly encouraged, not required for this assignment. I did the whole game with pure dom manipulation. Since I've only built class objects from the ground up and never migrated them over from plain variables and functions, I was hoping I could at least point me in the direction for how to start this process. So far when i try to think or google how I would do it I get a little freaked out that I'm going to have to start over. @thoughtbyte

**Comment by vabruzzo** [comment]
you handled this, closing
